from .system_base import (
    BASE_SYSTEM_INSTRUCTION,
    STUDENT_SYSTEM_PROMPT,
    TEACHER_SYSTEM_PROMPT,
    ADMIN_SYSTEM_PROMPT
)
from .student_prompts import (
    STUDENT_EXPLANATION_PROMPT,
    TEACHER_CLASS_BRIEFING_PROMPT,
    TEACHER_STUDENT_BRIEFING_PROMPT,
    ADMIN_EXECUTIVE_BRIEFING_PROMPT,
    STUDY_PLANNER_PROMPT
)

__all__ = [
    'BASE_SYSTEM_INSTRUCTION',
    'STUDENT_SYSTEM_PROMPT',
    'TEACHER_SYSTEM_PROMPT',
    'ADMIN_SYSTEM_PROMPT',
    'STUDENT_EXPLANATION_PROMPT',
    'TEACHER_CLASS_BRIEFING_PROMPT',
    'TEACHER_STUDENT_BRIEFING_PROMPT',
    'ADMIN_EXECUTIVE_BRIEFING_PROMPT',
    'STUDY_PLANNER_PROMPT',
]
