# Generated by Django 5.2.17 on 2026-08-16 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0003_academicyear_classsection_classschedule_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=200, verbose_name='intervention title')),
                ('category', models.CharField(choices=[('ACADEMIC_REMEDIAL', 'Topic / Academic Remediation'), ('ATTENDANCE_RECOVERY', 'Attendance Recovery Plan'), ('ASSIGNMENT_RECOVERY', 'Coursework & Assignment Support'), ('FACULTY_DIAGNOSTIC', 'Faculty Diagnostic Review'), ('THEORY_REINFORCEMENT', 'Theoretical Concept Reinforcement'), ('ENGAGEMENT_SUPPORT', 'Academic Engagement Check')], default='ACADEMIC_REMEDIAL', max_length=30, verbose_name='category')),
                ('status', models.CharField(choices=[('RECOMMENDED', 'Recommended (Pending Educator Review)'), ('APPROVED', 'Approved'), ('CREATED', 'Created'), ('ASSIGNED', 'Assigned to Student'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Actions Completed (Pending Evaluation)'), ('EVALUATING', 'In Evaluation Window'), ('EFFECTIVE', 'Effective'), ('PARTIALLY_EFFECTIVE', 'Partially Effective'), ('NO_MEASURABLE_CHANGE', 'No Measurable Change'), ('INEFFECTIVE', 'Ineffective'), ('ESCALATED', 'Escalated'), ('DISMISSED', 'Dismissed'), ('CLOSED', 'Closed & Archived')], default='RECOMMENDED', max_length=30, verbose_name='lifecycle status')),
                ('priority', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority'), ('URGENT', 'Urgent Priority')], default='MEDIUM', max_length=20, verbose_name='priority level')),
                ('primary_target_metric', models.CharField(choices=[('ATTENDANCE', 'Attendance Percentage'), ('ASSIGNMENT_COMPLETION', 'Assignment Completion Rate'), ('TOPIC_MASTERY', 'Topic Syllabus Mastery'), ('ASSESSMENT_PERFORMANCE', 'Weighted Course Performance'), ('THEORY_PERFORMANCE', 'Theoretical Exam Scores'), ('ANOMALY_RECOVERY', 'Performance Anomaly Recovery')], default='ASSESSMENT_PERFORMANCE', max_length=30, verbose_name='primary target metric')),
                ('evaluation_window', models.CharField(choices=[('DAYS_7', 'Immediate Window (7 Days)'), ('DAYS_14', 'Short Term Window (14 Days)'), ('DAYS_30', 'Standard Term Window (30 Days)'), ('NEXT_ASSESSMENT', 'Next Course Assessment')], default='DAYS_14', max_length=20, verbose_name='evaluation window')),
                ('objective', models.TextField(verbose_name='concrete learning / recovery objective')),
                ('educator_notes', models.TextField(blank=True, verbose_name='faculty observations & strategy')),
                ('due_date', models.DateField(verbose_name='action plan completion due date')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approval timestamp')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started timestamp')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='actions completed timestamp')),
                ('evaluated_at', models.DateTimeField(blank=True, null=True, verbose_name='impact evaluated timestamp')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed timestamp')),
                ('dismissed_at', models.DateTimeField(blank=True, null=True, verbose_name='dismissed timestamp')),
                ('dismissal_reason', models.TextField(blank=True, verbose_name='dismissal explanation')),
                ('trigger_insight_type', models.CharField(blank=True, max_length=50, verbose_name='trigger insight type')),
                ('baseline_metrics', models.JSONField(default=dict, verbose_name='frozen baseline snapshot at creation')),
                ('followup_metrics', models.JSONField(default=dict, verbose_name='frozen follow-up metrics at evaluation')),
                ('effectiveness_summary', models.TextField(blank=True, verbose_name='deterministic impact summary')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervised_interventions', to='academic.teacherprofile', verbose_name='supervising educator')),
                ('class_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='academic.classsection', verbose_name='class section')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='academic.course', verbose_name='target course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_interventions', to=settings.AUTH_USER_MODEL, verbose_name='author / initiator')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='academic.studentprofile', verbose_name='student')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='academic.topic', verbose_name='target syllabus topic')),
            ],
            options={
                'verbose_name': 'academic intervention',
                'verbose_name_plural': 'academic interventions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterventionAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Acknowledgment'), ('ACCEPTED', 'Accepted & Acknowledged by Student'), ('CLARIFICATION_REQUESTED', 'Clarification Requested by Student')], default='PENDING', max_length=30, verbose_name='acknowledgment status')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='acknowledged timestamp')),
                ('student_notes', models.TextField(blank=True, verbose_name='student feedback / clarification question')),
                ('intervention', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgement', to='interventions.intervention', verbose_name='parent intervention')),
            ],
            options={
                'verbose_name': 'intervention student acknowledgment',
                'verbose_name_plural': 'intervention student acknowledgments',
            },
        ),
        migrations.CreateModel(
            name='InterventionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order_index', models.PositiveSmallIntegerField(default=1, verbose_name='sequence order')),
                ('title', models.CharField(max_length=200, verbose_name='action title')),
                ('description', models.TextField(blank=True, verbose_name='detailed instructions & requirements')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped / Optional')], default='PENDING', max_length=20, verbose_name='action status')),
                ('verification_type', models.CharField(choices=[('STUDENT_CHECK', 'Student Self-Check'), ('EDUCATOR_VERIFIED', 'Faculty / Advisor Verified'), ('SYSTEM_AUTOMATIC', 'Automatic System Verification')], default='STUDENT_CHECK', max_length=30, verbose_name='verification type')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='action target due date')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completion timestamp')),
                ('completion_notes', models.TextField(blank=True, verbose_name='completion evidence / notes')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='interventions.intervention', verbose_name='parent intervention')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_intervention_actions', to='academic.learningresource', verbose_name='linked learning resource')),
            ],
            options={
                'verbose_name': 'intervention action item',
                'verbose_name_plural': 'intervention action items',
                'ordering': ['intervention', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='InterventionEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('escalated_to_role', models.CharField(max_length=50, verbose_name='target authority role')),
                ('reason', models.TextField(verbose_name='escalation justification')),
                ('previous_status', models.CharField(max_length=30, verbose_name='status prior to escalation')),
                ('escalated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='triggered_escalations', to=settings.AUTH_USER_MODEL, verbose_name='escalating actor')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='interventions.intervention', verbose_name='parent intervention')),
            ],
            options={
                'verbose_name': 'intervention escalation record',
                'verbose_name_plural': 'intervention escalation records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterventionEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('checkpoint_number', models.PositiveSmallIntegerField(default=1, verbose_name='checkpoint sequence number')),
                ('evaluation_type', models.CharField(choices=[('CHECKPOINT', 'Intermediate Progress Checkpoint'), ('FINAL_EVALUATION', 'Final Outcome Impact Evaluation')], default='CHECKPOINT', max_length=30, verbose_name='evaluation type')),
                ('classification', models.CharField(choices=[('EFFECTIVE', 'Effective (Target Metric Measurably Improved)'), ('PARTIALLY_EFFECTIVE', 'Partially Effective (Target Improved, Mixed Secondary)'), ('NO_MEASURABLE_CHANGE', 'No Measurable Change'), ('INEFFECTIVE', 'Ineffective (Target Deteriorated or Persistent Risk)'), ('INSUFFICIENT_DATA', 'Insufficient Post-Intervention Data')], default='INSUFFICIENT_DATA', max_length=30, verbose_name='effectiveness classification')),
                ('metrics_snapshot', models.JSONField(default=dict, verbose_name='metrics snapshot at checkpoint')),
                ('delta_metrics', models.JSONField(default=dict, verbose_name='metric movements relative to baseline')),
                ('progress_percentage', models.FloatField(default=0.0, verbose_name='action checklist progress %')),
                ('evaluation_notes', models.TextField(blank=True, verbose_name='evaluator commentary & observations')),
                ('data_quality', models.CharField(default='VALID', max_length=30, verbose_name='data quality rating')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conducted_intervention_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='evaluating educator')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='interventions.intervention', verbose_name='intervention')),
            ],
            options={
                'verbose_name': 'intervention evaluation checkpoint',
                'verbose_name_plural': 'intervention evaluation checkpoints',
                'ordering': ['intervention', 'checkpoint_number'],
            },
        ),
    ]
