"""
Institutional Reporting & CSV Export Engine.
Produces standard CSV files and print-ready structured report datasets.
Enforces strict RBAC and authentic fact citations.
"""

import csv
from typing import Dict, Any, List
from django.http import HttpResponse
from django.utils import timezone
from django.core.exceptions import PermissionDenied
from apps.core.models import User
from apps.academic.models import (
    StudentProfile,
    TeacherProfile,
    Department,
    ClassSection,
    Enrollment
)
from apps.interventions.models import Intervention
from .transcript_service import TranscriptService


class ReportingService:
    """
    Assembles and exports academic reports.
    """

    @classmethod
    def export_student_transcript_csv(cls, student: StudentProfile) -> HttpResponse:
        """
        Generates official CSV transcript export.
        """
        data = TranscriptService.get_student_transcript(student)
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = f'attachment; filename="transcript_{student.student_id}.csv"'

        writer = csv.writer(response)
        writer.writerow(["OFFICIAL ACADEMIC TRANSCRIPT"])
        writer.writerow(["Institution", "Education Management Portal"])
        writer.writerow(["Student ID", data['student_id']])
        writer.writerow(["Student Name", data['student_name']])
        writer.writerow(["Department", data['department_name']])
        writer.writerow(["Program", data['program_name']])
        writer.writerow(["Cumulative GPA", data['cumulative_gpa']])
        writer.writerow(["Credits Earned", data['total_credits_earned']])
        writer.writerow(["Academic Standing", data['academic_standing']])
        writer.writerow([])

        writer.writerow(["Semester", "Academic Year", "Course Code", "Course Title", "Credits", "Grade Letter", "Percentage", "Attendance %"])
        for sem in data['semesters']:
            for c in sem['courses']:
                writer.writerow([
                    sem['semester_name'],
                    sem['academic_year'],
                    c['course_code'],
                    c['course_title'],
                    c['credits'],
                    c['grade_letter'],
                    c['final_percentage'] if c['final_percentage'] is not None else 'N/A',
                    f"{c['attendance_percentage']}%"
                ])

        return response

    @classmethod
    def export_teacher_section_csv(cls, teacher: TeacherProfile, section_id: int) -> HttpResponse:
        """
        Generates Section Roster, Performance, and Attendance CSV export for teacher.
        """
        sec = ClassSection.objects.filter(pk=section_id, primary_teacher=teacher).select_related('course', 'semester').first()
        if not sec:
            raise PermissionDenied("Unauthorized section export.")

        enrs = sec.enrollments.filter(status='ENROLLED').select_related('student__user')
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = f'attachment; filename="section_{sec.course.code}_{sec.section_code}.csv"'

        writer = csv.writer(response)
        writer.writerow(["CLASS SECTION PERFORMANCE & ATTENDANCE REPORT"])
        writer.writerow(["Course", f"{sec.course.code} - {sec.course.title}"])
        writer.writerow(["Section", sec.section_code])
        writer.writerow(["Instructor", teacher.user.get_full_name()])
        writer.writerow(["Semester", sec.semester.name])
        writer.writerow(["Generated At", timezone.now().strftime("%Y-%m-%d %H:%M:%S UTC")])
        writer.writerow([])

        writer.writerow(["Student ID", "Student Name", "Email", "Final Grade Letter", "Final Percentage"])
        for enr in enrs:
            writer.writerow([
                enr.student.student_id,
                enr.student.user.get_full_name(),
                enr.student.user.email,
                enr.final_grade_letter or 'In Progress',
                enr.final_percentage if enr.final_percentage is not None else 'In Progress'
            ])

        return response

    @classmethod
    def export_admin_institutional_csv(cls, admin_user: User) -> HttpResponse:
        """
        Generates macro institutional academic performance CSV export.
        """
        departments = Department.objects.all()
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = f'attachment; filename="institutional_report_{timezone.now().strftime("%Y%m%d")}.csv"'

        writer = csv.writer(response)
        writer.writerow(["UNIVERSITY-WIDE ACADEMIC INTELLIGENCE STATEMENT"])
        writer.writerow(["Generated By", admin_user.email])
        writer.writerow(["Generated At", timezone.now().strftime("%Y-%m-%d %H:%M:%S UTC")])
        writer.writerow([])

        writer.writerow(["Department Code", "Department Name", "Total Programs", "Total Courses", "Total Active Enrollments"])
        for dept in departments:
            prog_count = dept.programs.count()
            course_count = dept.courses.count()
            enr_count = Enrollment.objects.filter(class_section__course__department=dept, status='ENROLLED').count()
            writer.writerow([dept.code, dept.name, prog_count, course_count, enr_count])

        return response

    @classmethod
    def export_admin_interventions_csv(cls, admin_user: User) -> HttpResponse:
        """
        Generates institutional intervention oversight and impact CSV export.
        """
        intvs = Intervention.objects.select_related('student__user', 'course', 'assigned_to__user').all()
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = f'attachment; filename="interventions_audit_{timezone.now().strftime("%Y%m%d")}.csv"'

        writer = csv.writer(response)
        writer.writerow(["CLOSED-LOOP ACADEMIC INTERVENTIONS AUDIT STATEMENT"])
        writer.writerow(["Generated At", timezone.now().strftime("%Y-%m-%d %H:%M:%S UTC")])
        writer.writerow([])

        writer.writerow(["ID", "Student ID", "Student Name", "Course", "Category", "Priority", "Status", "Outcome Evaluated", "Due Date", "Supervisor"])
        for iv in intvs:
            writer.writerow([
                iv.pk,
                iv.student.student_id,
                iv.student.user.get_full_name(),
                iv.course.code,
                iv.get_category_display(),
                iv.get_priority_display(),
                iv.get_status_display(),
                iv.is_effective_display if hasattr(iv, 'is_effective_display') else iv.status,
                str(iv.due_date),
                iv.assigned_to.user.get_full_name() if iv.assigned_to else "Advisor"
            ])

        return response
