# Generated by Django 5.2.17 on 2026-08-16 05:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('employee_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='employee ID')),
                ('designation', models.CharField(default='Assistant Professor', max_length=100, verbose_name='designation')),
                ('qualification', models.CharField(blank=True, max_length=200, verbose_name='qualification')),
                ('office_location', models.CharField(blank=True, max_length=100, verbose_name='office location')),
                ('joining_date', models.DateField(default=django.utils.timezone.now, verbose_name='joining date')),
            ],
            options={
                'verbose_name': 'teacher profile',
                'verbose_name_plural': 'teacher profiles',
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('degree_level', models.CharField(choices=[('BACHELOR', 'Bachelor Degree'), ('MASTER', 'Master Degree'), ('DOCTORATE', 'Doctorate / PhD'), ('DIPLOMA', 'Diploma / Certificate')], default='BACHELOR', max_length=20, verbose_name='degree level')),
                ('duration_years', models.PositiveSmallIntegerField(default=4, verbose_name='duration in years')),
                ('total_semesters', models.PositiveSmallIntegerField(default=8, verbose_name='total semesters')),
                ('is_active', models.BooleanField(default=True, verbose_name='active status')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academic.department', verbose_name='department')),
            ],
            options={
                'verbose_name': 'program',
                'verbose_name_plural': 'programs',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('student_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='student ID / roll number')),
                ('current_semester', models.PositiveSmallIntegerField(default=1, verbose_name='current semester')),
                ('academic_year', models.PositiveSmallIntegerField(default=2026, verbose_name='academic year')),
                ('academic_status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('PROBATION', 'Academic Probation'), ('GRADUATED', 'Graduated'), ('WITHDRAWN', 'Withdrawn')], default='ACTIVE', max_length=20, verbose_name='academic status')),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now, verbose_name='enrollment date')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academic.department', verbose_name='department')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academic.program', verbose_name='academic program')),
            ],
            options={
                'verbose_name': 'student profile',
                'verbose_name_plural': 'student profiles',
                'ordering': ['student_id'],
            },
        ),
    ]
