# Generated by Django 5.2.17 on 2026-08-16 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('notification_type', models.CharField(choices=[('ATTENDANCE_WARNING', 'Attendance Warning'), ('ASSIGNMENT_DEADLINE', 'Assignment Deadline'), ('ASSIGNMENT_OVERDUE', 'Assignment Overdue'), ('GRADE_PUBLISHED', 'Grade Published'), ('ANNOUNCEMENT', 'Course Announcement'), ('INTERVENTION_ASSIGNED', 'Support Plan Assigned'), ('INTERVENTION_ACTION_DUE', 'Support Action Due'), ('INTERVENTION_OVERDUE', 'Support Action Overdue'), ('RISK_ESCALATION', 'Risk Escalation Alert'), ('ACUTE_ANOMALY', 'Acute Performance Anomaly'), ('SYSTEM_ALERT', 'System Alert'), ('DIGEST_SUMMARY', 'Periodic Academic Digest')], db_index=True, default='SYSTEM_ALERT', max_length=40, verbose_name='notification type')),
                ('priority', models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], db_index=True, default='INFO', max_length=20, verbose_name='priority')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('link_url', models.CharField(blank=True, max_length=500, verbose_name='link URL')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='is read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read timestamp')),
                ('event_hash', models.CharField(db_index=True, help_text='SHA-256 hash preventing duplicate notifications for the same trigger event.', max_length=64, verbose_name='deduplication event hash')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('enable_academic_alerts', models.BooleanField(default=True, help_text='Critical academic safety alerts are mandatory and cannot be disabled.', verbose_name='enable academic & risk alerts')),
                ('enable_assignment_reminders', models.BooleanField(default=True, verbose_name='enable assignment reminders')),
                ('enable_attendance_warnings', models.BooleanField(default=True, verbose_name='enable attendance warnings')),
                ('enable_intervention_updates', models.BooleanField(default=True, verbose_name='enable support plan updates')),
                ('enable_ai_insights', models.BooleanField(default=True, verbose_name='enable AI periodic summaries')),
                ('enable_announcements', models.BooleanField(default=True, verbose_name='enable course announcements')),
                ('digest_frequency', models.CharField(choices=[('DAILY', 'Daily Summary'), ('WEEKLY', 'Weekly Summary'), ('NONE', 'No Digest')], default='DAILY', max_length=20, verbose_name='digest frequency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
            },
        ),
    ]
