# Generated by Django 5.2.17 on 2026-08-16 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('role', models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], max_length=20, verbose_name='user role')),
                ('title', models.CharField(default='Academic Advisory Session', max_length=255, verbose_name='conversation title')),
                ('context_scope', models.JSONField(blank=True, default=dict, help_text='UI filter metadata only. Never trusted as an authorization bypass.', verbose_name='context scope metadata')),
                ('summary', models.TextField(blank=True, default='', verbose_name='compressed conversation summary')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archived status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'AI Conversation',
                'verbose_name_plural': 'AI Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIInteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20, verbose_name='role')),
                ('request_type', models.CharField(max_length=50, verbose_name='request type')),
                ('provider', models.CharField(max_length=50, verbose_name='AI provider')),
                ('model', models.CharField(max_length=100, verbose_name='model identifier')),
                ('prompt_version', models.CharField(max_length=50, verbose_name='prompt version')),
                ('latency_ms', models.PositiveIntegerField(default=0, verbose_name='latency ms')),
                ('success', models.BooleanField(default=True, verbose_name='success status')),
                ('validation_status', models.CharField(default='VALID', max_length=50, verbose_name='validation status')),
                ('error_code', models.CharField(blank=True, default='', max_length=100, verbose_name='error code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_interaction_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'AI Interaction Log',
                'verbose_name_plural': 'AI Interaction Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'AI Academic Assistant'), ('SYSTEM', 'System Instructions'), ('TOOL', 'Deterministic Tool Result')], default='USER', max_length=20, verbose_name='sender type')),
                ('content', models.TextField(verbose_name='message content')),
                ('structured_payload', models.JSONField(blank=True, default=dict, help_text='Contains fact attribution, calculations, simulations, actions, and validation status.', verbose_name='structured response payload')),
                ('token_count', models.PositiveIntegerField(default=0, verbose_name='estimated tokens')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_service.aiconversation', verbose_name='conversation')),
            ],
            options={
                'verbose_name': 'AI Message',
                'verbose_name_plural': 'AI Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessageFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_helpful', models.BooleanField(verbose_name='helpful')),
                ('category', models.CharField(blank=True, choices=[('INCORRECT_INFO', 'Incorrect Information'), ('NOT_RELEVANT', 'Not Relevant'), ('TOO_VAGUE', 'Too Vague'), ('MISSING_CONTEXT', 'Missing Context'), ('OTHER', 'Other')], default='', max_length=30, verbose_name='feedback category')),
                ('comments', models.TextField(blank=True, default='', verbose_name='user comments')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ai_service.aimessage', verbose_name='AI message')),
            ],
            options={
                'verbose_name': 'AI Message Feedback',
                'verbose_name_plural': 'AI Message Feedbacks',
            },
        ),
    ]
